### ISSUE TITLE
Make tutorial and notebook text pedagogical

### ISSUE THREAD

**Issue by bnord** [lsst-epo/citizen-science-notebooks#26] opened 2023-03-09 17:42 UTC

**Comment by bnord** [comment] 2023-03-09 21:52
Documentation sufficient such that it can be approached in a “stand alone” way

**Comment by bnord** [comment] 2023-03-09 21:52
Includes examples of retrieving “common” data types from RSP?

**Comment by clareh** [comment] 2023-04-05 19:21
Just making a note of when we get to this, important to consider the error messages and read outs from the cells (consider any changes to the "send data" cell responses?)

**Comment by beckynevin** [comment] 2023-07-20 15:32
I'm going to close this issue; it was a duplicate of discussion #42 and was addressed in the clarifying_pedagogy pull request #48

**Closed by beckynevin** 2023-07-20 15:32 UTC
Labels: documentation, enhancement
